name: Deploy FrontEnd to Cloud Run

on:
  pull_request:
    branches: [ main ]

env:
  SERVICE_NAME: abcall

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout codigo
      uses: actions/checkout@v3

    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18.x'
        cache: 'npm'

    - name: Instalar dependencias
      run: |
        npm ci
        npm install -g @angular/cli

    - name: Verificar build Angular
      run: |
        ng build --configuration production
        if [ ! -d "dist/proyecto-angular" ]; then
          echo "Error: Build directory not found"
          exit 1
        fi

    - name: Autenticar en Google Cloud
      id: auth
      uses: google-github-actions/auth@v1
      with:
        credentials_json: ${{ secrets.GCP_SA_KEY }}

    - name: Configurar Google Cloud SDK
      uses: google-github-actions/setup-gcloud@v1
      with:
        project_id: ${{ secrets.PROJECT_ID }}

    - name: Instalar componentes beta
      run: |
        gcloud components install beta --quiet

    - name: Build y Push Docker
      run: |
        gcloud auth configure-docker --quiet
        docker build --progress=plain -t gcr.io/${{ secrets.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }} .
        docker push gcr.io/${{ secrets.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}

    - name: Deploy to Cloud Run
      id: deploy
      uses: google-github-actions/deploy-cloudrun@v1
      with:
        service: ${{ env.SERVICE_NAME }}
        image: gcr.io/${{ secrets.PROJECT_ID }}/${{ env.SERVICE_NAME }}:${{ github.sha }}
        region: ${{ secrets.REGION }}
        flags: |
          --allow-unauthenticated
          --port=8080
          --timeout=300
          --cpu=1
          --memory=512Mi
          --min-instances=1
          --max-instances=10
          --ingress=all
          --execution-environment=gen2

    - name: Verificar Deploy
      if: always()
      run: |
        echo "Verificando estado del servicio..."
        gcloud run services describe ${{ env.SERVICE_NAME }} \
        --region ${{ secrets.REGION }} \
        --format='get(status.conditions)'

        echo "Últimos logs del servicio:"
        gcloud beta run services logs read ${{ env.SERVICE_NAME }} \
        --region ${{ secrets.REGION }} \
        --limit=50